from fastapi import APIRouter, Depends, Response, HTTPException
from pydantic import BaseModel
from typing import List
from app.core.security import require_role
import io

router = APIRouter(prefix="/exports", tags=["export-ebu"])

class EBUExportRequest(BaseModel):
    project_id: int
    replicas: List[dict]
    metadata: dict = {}

@router.post("/ebu-stl")
async def export_ebu_stl(request: EBUExportRequest, current_user=Depends(require_role("adaptateur"))):
    """
    G-2.5 — EBU-STL extended export.
    Simplified STL format (real implementation would use proper EBU-STL library).
    """
    content = io.StringIO()
    content.write("EBU-STL\n")
    content.write(f"Project: {request.project_id}\n")
    content.write(f"Generated by: {current_user.sub}\n\n")
    
    for i, rep in enumerate(request.replicas, 1):
        start = rep["start_ms"] / 1000
        end = rep["end_ms"] / 1000
        content.write(f"{i:03d} {start:07.3f} {end:07.3f} {rep.get('speaker_id', 1):02d} {rep['text']}\n")
    
    return Response(
        content=content.getvalue(),
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=project_{request.project_id}.stl"}
    )
